name: Liquibase Deploy

on:
  workflow_dispatch:   # Manual run enable
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Microsoft JDBC Driver
      run: |
        curl -L https://github.com/microsoft/mssql-jdbc/releases/download/v12.6.0/mssql-jdbc-12.6.0.jre17.jar -o mssql-jdbc.jar

    - name: Run Liquibase update
      uses: liquibase/liquibase-github-action@v7
      with:
        operation: update
        changelogFile: db.changelog-master.xml
        url: ${{ secrets.DB_URL }}
        username: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASS }}
        classpath: mssql-jdbc.jar
